//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autotinklo_Informacine_sistema
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autodalis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Autodalis()
        {
            this.Autodalies_uzsakymas = new HashSet<Autodalies_uzsakymas>();
        }
    
        public int id { get; set; }
        public string pavadinimas { get; set; }
        public Nullable<double> kaina { get; set; }
        public string gamintojas { get; set; }
        public Nullable<int> fk_parduotuve { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Autodalies_uzsakymas> Autodalies_uzsakymas { get; set; }
        public virtual Parduotuve Parduotuve { get; set; }
    }
}
