//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Autotinklo_Informacine_sistema
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AutotinklasDMContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AutotinklasDMContainer object using the connection string found in the 'AutotinklasDMContainer' section of the application configuration file.
        /// </summary>
        public AutotinklasDMContainer() : base("name=AutotinklasDMContainer", "AutotinklasDMContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AutotinklasDMContainer object.
        /// </summary>
        public AutotinklasDMContainer(string connectionString) : base(connectionString, "AutotinklasDMContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AutotinklasDMContainer object.
        /// </summary>
        public AutotinklasDMContainer(EntityConnection connection) : base(connection, "AutotinklasDMContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
    }

    #endregion

}
