//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autotinklo_Informacine_sistema
{
    using System;
    using System.Collections.Generic;
    
    public partial class Darbuotojas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Darbuotojas()
        {
            this.Uzsakymas = new HashSet<Uzsakymas>();
        }
    
        public int id { get; set; }
        public string pavarde { get; set; }
        public string vardas { get; set; }
        public string adresas { get; set; }
        public string telefonas { get; set; }
        public Nullable<int> fk_Padalinys { get; set; }
    
        public virtual Padalinys Padalinys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Uzsakymas> Uzsakymas { get; set; }
    }
}
