//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autotinklo_Informacine_sistema
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uzsakymas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Uzsakymas()
        {
            this.Autodalies_uzsakymas = new HashSet<Autodalies_uzsakymas>();
            this.Gedimas = new HashSet<Gedimas>();
            this.Saskaita = new HashSet<Saskaita>();
        }
    
        public int uzsakymo_nr { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public string kliento_vardas { get; set; }
        public string kliento_pavarde { get; set; }
        public string kliento_telefonas { get; set; }
        public Nullable<int> fk_meistras { get; set; }
        public string fk_automobilis { get; set; }
        public string fk_pakaitinis_automobilis { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Autodalies_uzsakymas> Autodalies_uzsakymas { get; set; }
        public virtual Automobilis Automobilis { get; set; }
        public virtual Darbuotojas Darbuotojas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gedimas> Gedimas { get; set; }
        public virtual Pakaitinis_automobilis Pakaitinis_automobilis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Saskaita> Saskaita { get; set; }
    }
}
