//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutotinklasInformacinėSistema
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Autodalies_uzsakymas
    {
        public int id { get; set; }
        [Required(ErrorMessage = "Būtina įvesti prekių kiekį")]
        public Nullable<int> kiekis { get; set; }
        public Nullable<int> fk_autodalis { get; set; }
        public Nullable<int> fk_uzsakymas { get; set; }
    
        public virtual Autodalis Autodalis { get; set; }
        public virtual Uzsakymas Uzsakymas { get; set; }
    }
}
