//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutotinklasInformacinėSistema
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AutotinklasDBEntities : DbContext
    {
        public AutotinklasDBEntities()
            : base("name=AutotinklasDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Autodalies_uzsakymas> Autodalies_uzsakymas { get; set; }
        public virtual DbSet<Autodalis> Autodalis { get; set; }
        public virtual DbSet<Automobilis> Automobilis { get; set; }
        public virtual DbSet<Darbuotojas> Darbuotojas { get; set; }
        public virtual DbSet<Gedimas> Gedimas { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<Marke> Marke { get; set; }
        public virtual DbSet<Modelis> Modelis { get; set; }
        public virtual DbSet<Padalinys> Padalinys { get; set; }
        public virtual DbSet<Pakaitinis_automobilis> Pakaitinis_automobilis { get; set; }
        public virtual DbSet<Parduotuve> Parduotuve { get; set; }
        public virtual DbSet<Saskaita> Saskaita { get; set; }
        public virtual DbSet<Uzsakymas> Uzsakymas { get; set; }
    }
}
