//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutotinklasInformacinėSistema
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Automobilis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Automobilis()
        {
            this.Uzsakymas = new HashSet<Uzsakymas>();
        }
        [Required(ErrorMessage = "Būtina įvesti valstybinį numerį")]
        public string valstybinis_numeris { get; set; }
        [Required(ErrorMessage = "Būtina įvesti kėbulo tipą")]
        public string kebulo_tipas { get; set; }
        [Required(ErrorMessage = "Būtina įvesti kebulo numerį")]
        public string kebulo_numeris { get; set; }
        [Required(ErrorMessage = "Būtina įvesti automobilio gamybos metus")]
        public string metai { get; set; }
        public Nullable<int> fk_modelis { get; set; }
    
        public virtual Modelis Modelis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Uzsakymas> Uzsakymas { get; set; }
    }
}
