//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutotinklasInformacinėSistema
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Gedimas
    {
        public int id { get; set; }
        [Required(ErrorMessage = "Būtina įvesti aprašymą")]
        public string pavadinimas { get; set; }
        public Nullable<int> fk_uzsakymas { get; set; }
    
        public virtual Uzsakymas Uzsakymas { get; set; }
    }
}
