//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutotinklasInformacinėSistema
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Modelis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Modelis()
        {
            this.Automobilis = new HashSet<Automobilis>();
            this.Pakaitinis_automobilis = new HashSet<Pakaitinis_automobilis>();
        }
    
        public int id { get; set; }
        [Required(ErrorMessage = "Būtina įvesti modelį")]
        public string pavadinimas { get; set; }
        public Nullable<int> fk_marke { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Automobilis> Automobilis { get; set; }
        public virtual Marke Marke { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pakaitinis_automobilis> Pakaitinis_automobilis { get; set; }
    }
}
