//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutotinklasInformacinėSistema
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Parduotuve
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Parduotuve()
        {
            this.Autodalis = new HashSet<Autodalis>();
        }
    
        public int id { get; set; }
        [Required(ErrorMessage = "Būtina įvesti pavadinimą")]
        public string pavadinimas { get; set; }
        [Required(ErrorMessage = "Būtina įvesti miestą")]
        public string miestas { get; set; }
        [Required(ErrorMessage = "Būtina įvesti adresą")]
        public string adresas { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Autodalis> Autodalis { get; set; }
    }
}
